server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: foj-backend
    # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/foj
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    # 仅在开发环境下打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: is_delete #全局逻辑删除实体字段名
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.defen.fojbackend.controller